# Cost parameters.
SLACK_COST = 500000

# Column generation settings.
PRECISION = 0.0001
START_EXACT_PRICING = true
SWITCH_TO_EXACT_PRICING = true
MAX_COLS_PER_PRICING_PROBLEM = 50
NUM_THREADS = 8
NUM_THREADS_SOLVER = 6

# Primal heuristic.
PRIMAL_HEURISTIC_FREQUENCY = 1

# Dual smoothing parameters.
ALPHA = 0.5
ALPHA_UB = 0.9
AUTO_TUNE_ALPHA = false
USE_LAGRANGIAN_SMOOTHING = false

# Strong branching
NUM_THREADS_STRONG_BRANCHING = 4
NUM_THREADS_STRONG_BRANCHING_SOLVER = 4
NUM_STRONG_BRANCHING_CANDIDATES = 1
NUM_STRONG_BRANCHING_STRONG_CANDIDATES = 1
NUM_STRONG_BRANCHING_ITERATIONS = 5

# Column management settings.
COLUMN_REMOVAL_FREQUENCY = 5
COLUMN_REMOVAL_THRESHOLD = 10
MINIMUM_NUMBER_NON_BASIC = 1000

# Cut management settings.
CUT_REMOVAL_FREQUENCY = 0
CUT_REMOVAL_THRESHOLD = 15

# Enumeration.
RMH_FREQUENCY = 10
RMH_TIME_LIMIT = 5
HEURISTIC_ENUMERATION_THRESHOLD = 0 
ENUMERATION_THRESHOLD = 0
MAX_ENUMERATED_COLUMNS = 0
MAX_RMH_COLUMNS = 0

# Output settings.
OUTPUT_SEPARATOR = ;